{"author":{"id":"8dc3c6364934ad6e21af001c5b6df2e7838b8a22b9e09528e1ac98a46b4d6c5f"},"ops":[{"type":1,"timestamp":1615523129,"nonce":"4wGWK/HS7bBHW1e9z0+rW7ngFE8=","metadata":{"github-id":"MDU6SXNzdWU4Mjk3NDU0NDQ=","github-url":"https://github.com/svpcom/wfb-ng/issues/120","origin":"github"},"title":"make deb fail","message":"uname -a\nLinux faith 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux\n\n\nmake deb fail:\n\n\nmake[2]: Entering directory '/home/faith/wifi_vtx/deb_dist/wifibroadcast-21.3.12.15779'\npython setup.py install --force --root=debian/wifibroadcast --no-compile -O0 --install-layout=deb --prefix=/usr\nusage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n   or: setup.py --help [cmd1 cmd2 ...]\n   or: setup.py --help-commands\n   or: setup.py cmd --help\n\nerror: option --install-layout not recognized\ndebian/rules:17: recipe for target 'override_dh_auto_install' failed\nmake[2]: *** [override_dh_auto_install] Error 1\nmake[2]: Leaving directory '/home/faith/wifi_vtx/deb_dist/wifibroadcast-21.3.12.15779'\ndebian/rules:7: recipe for target 'binary' failed\nmake[1]: *** [binary] Error 2\nmake[1]: Leaving directory '/home/faith/wifi_vtx/deb_dist/wifibroadcast-21.3.12.15779'\ndpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2\nTraceback (most recent call last):\n  File \"./setup.py\", line 82, in \u003cmodule\u003e\n    license=\"GPLv3\",\n  File \"/home/faith/wifi_vtx/env/local/lib/python2.7/site-packages/setuptools/__init__.py\", line 162, in setup\n    return distutils.core.setup(**attrs)\n  File \"/usr/lib/python2.7/distutils/core.py\", line 151, in setup\n    dist.run_commands()\n  File \"/usr/lib/python2.7/distutils/dist.py\", line 953, in run_commands\n    self.run_command(cmd)\n  File \"/usr/lib/python2.7/distutils/dist.py\", line 972, in run_command\n    cmd_obj.run()\n  File \"/home/faith/wifi_vtx/env/local/lib/python2.7/site-packages/stdeb/command/bdist_deb.py\", line 67, in run\n    util.process_command(syscmd, cwd=target_dirs[0])\n  File \"/home/faith/wifi_vtx/env/local/lib/python2.7/site-packages/stdeb/util.py\", line 227, in process_command\n    check_call(args, cwd=cwd)\n  File \"/home/faith/wifi_vtx/env/local/lib/python2.7/site-packages/stdeb/util.py\", line 59, in check_call\n    raise CalledProcessError(retcode)\nstdeb.util.CalledProcessError: 2\nMakefile:52: recipe for target 'deb' failed\nmake: *** [deb] Error 1","files":null}]}