{"author":{"id":"f4601368af118241a0730afd24caa7d4cc38ae8f9a013ed93ad685a10f032a2d"},"ops":[{"type":6,"timestamp":1575505841,"nonce":"bO1TaLoWr/ncChSoIz+b+xhBYWE=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDMxOTc4ODg3NA=="},"target":"fb7d579abb67f457e2a0ee59a54e48cb31f987a5a8f421a2960f7bbe9e3843cd","message":"Fresh build and install, on two Raspberry Pi 3Bs. \n\nI get this error after adding the UdpEndpoint to the config file:\n\n```\npi@sparky-gcs:~ $ wfb-cli\nConfig parse error: [UdpEndpoint wifibroadcast] mode = Normal\nTraceback (most recent call last):\n  File \"/usr/bin/wfb-cli\", line 11, in \u003cmodule\u003e\n    load_entry_point('wifibroadcast==19.12.4.85045', 'console_scripts', 'wfb-cli')()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 489, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2793, in load_entry_point\n    return ep.load()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2411, in load\n    return self.resolve()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2417, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\n  File \"/usr/lib/python2.7/dist-packages/telemetry/cli.py\", line 40, in \u003cmodule\u003e\n    from telemetry.common import abort_on_crash, exit_status\n  File \"/usr/lib/python2.7/dist-packages/telemetry/common.py\", line 33, in \u003cmodule\u003e\n    from telemetry.conf import settings\n  File \"/usr/lib/python2.7/dist-packages/telemetry/conf/__init__.py\", line 25, in \u003cmodule\u003e\n    settings, cfg_files = _parse_config()\n  File \"/usr/lib/python2.7/dist-packages/telemetry/conf/__init__.py\", line 22, in _parse_config\n    return config_parser.parse_config(os.path.join(os.getcwd(), os.path.dirname(__file__)), telemetry_cfg or _cfg_files)\n  File \"/usr/lib/python2.7/dist-packages/telemetry/config_parser.py\", line 106, in parse_config\n    raise ConfigError('Parse error: %s' % (err,))\ntelemetry.config_parser.ConfigError: Parse error: [UdpEndpoint wifibroadcast] mode = Normal\n\n```\n\n\nHere's my /etc/wifibroadcast.cfg:\n\n```\n[common]\nwifi_channel = 161     # 161 -- radio channel @5825 MHz, range: 5815â€“5835 MHz, width 20MHz\n                       # 1 -- radio channel @2412 Mhz, \n                       # see https://en.wikipedia.org/wiki/List_of_WLAN_channels for reference\nwifi_region = 'US'     # Your country for CRDA (use BO or GY if you want max tx power)  \n\n[gs_mavlink]\npeer = 'connect://127.0.0.1:14550'  # outgoing connection\n# peer = 'listen://0.0.0.0:14550'   # incoming connection\n\n[gs_video]\npeer = 'connect://127.0.0.1:5600'  # outgoing connection for\n                                   # video sink (QGroundControl on GS)\n\n\n[UdpEndpoint wifibroadcast]\nMode = Normal\nAddress = 127.0.0.1\nPort = 14550\n\n```\n\nAny ideas why I'm getting this? I followed the instructions exactly.\n\nThanks for reading!","files":null}]}