{"author":{"id":"f6e2c84cbd41daecf4582d969b556a96eb202b5bed142fd85d6e07732fc4fe19"},"ops":[{"type":3,"timestamp":1713564825,"nonce":"8+jRXilt8M9EWsqGnh5zZtoGmcs=","metadata":{"github-id":"IC_kwDOBLCY8M57OS5R","github-url":"https://github.com/svpcom/wfb-ng/issues/333#issuecomment-2067344977"},"message":"\u003e Try without virtualenv/venv:\n\u003e \n\u003e ```\n\u003e pip3 install --user stdeb\n\u003e python3 ./setup.py --command-packages=stdeb bdist_deb\n\u003e ```\n\nOK, I have googled some issue, which might be related to specific python version. I'm NOT sure if it's python 3.10\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip3 install --user stdeb\nRequirement already satisfied: stdeb in /home/daniel/.local/lib/python3.10/site-packages (0.10.0)\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 ./setup.py --command-packages=stdeb bdist_deb\nTraceback (most recent call last):\n  File \"/home/daniel/wfb/wfb-ng/./setup.py\", line 39, in \u003cmodule\u003e\n    setup(\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/__init__.py\", line 104, in setup\n    return distutils.core.setup(**attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 146, in setup\n    _setup_distribution = dist = klass(attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 318, in __init__\n    self.metadata.version = self._normalize_version(self.metadata.version)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 354, in _normalize_version\n    normalized = str(Version(version))\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\nsetuptools.extern.packaging.version.InvalidVersion: Invalid version: 'trunk'\n```","files":null},{"type":6,"timestamp":1713564952,"nonce":"PcoJWKtVlu8kj0DKFk3vtzOBWn8=","metadata":{"github-id":"UCE_lALOBLCY8M57OS5RzkSfHcg"},"target":"5247880b60e1fe7f988d2099a9efa2d0a419b3cbce693a5e96906c277b924a77","message":"\u003e Try without virtualenv/venv:\n\u003e \n\u003e ```\n\u003e pip3 install --user stdeb\n\u003e python3 ./setup.py --command-packages=stdeb bdist_deb\n\u003e ```\n\nOK, I have googled some issues, which might be related to specific python version. I'm NOT sure if it's python 3.10\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip3 install --user stdeb\nRequirement already satisfied: stdeb in /home/daniel/.local/lib/python3.10/site-packages (0.10.0)\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 ./setup.py --command-packages=stdeb bdist_deb\nTraceback (most recent call last):\n  File \"/home/daniel/wfb/wfb-ng/./setup.py\", line 39, in \u003cmodule\u003e\n    setup(\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/__init__.py\", line 104, in setup\n    return distutils.core.setup(**attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 146, in setup\n    _setup_distribution = dist = klass(attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 318, in __init__\n    self.metadata.version = self._normalize_version(self.metadata.version)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 354, in _normalize_version\n    normalized = str(Version(version))\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\nsetuptools.extern.packaging.version.InvalidVersion: Invalid version: 'trunk'\n```","files":null},{"type":6,"timestamp":1713565274,"nonce":"HQwz+C4gbYCVw8n/7WyQzg4Bo6A=","metadata":{"github-id":"UCE_lALOBLCY8M57OS5RzkSfLeg"},"target":"5247880b60e1fe7f988d2099a9efa2d0a419b3cbce693a5e96906c277b924a77","message":"\u003e Try without virtualenv/venv:\n\u003e \n\u003e ```\n\u003e pip3 install --user stdeb\n\u003e python3 ./setup.py --command-packages=stdeb bdist_deb\n\u003e ```\n\nOK, I have googled some issues, which might be related to specific python version. I'm NOT sure if it's python 3.10\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip3 install --user stdeb\nRequirement already satisfied: stdeb in /home/daniel/.local/lib/python3.10/site-packages (0.10.0)\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 ./setup.py --command-packages=stdeb bdist_deb\nTraceback (most recent call last):\n  File \"/home/daniel/wfb/wfb-ng/./setup.py\", line 39, in \u003cmodule\u003e\n    setup(\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/__init__.py\", line 104, in setup\n    return distutils.core.setup(**attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 146, in setup\n    _setup_distribution = dist = klass(attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 318, in __init__\n    self.metadata.version = self._normalize_version(self.metadata.version)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 354, in _normalize_version\n    normalized = str(Version(version))\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\nsetuptools.extern.packaging.version.InvalidVersion: Invalid version: 'trunk'\n```\n\n-- EDIT\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip list | grep setuptools\nsetuptools                   69.5.1\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ which python\n/usr/bin/python\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ ls -l /usr/bin/python\nlrwxrwxrwx 1 root root 7 10月 11  2021 /usr/bin/python -\u003e python3\n```\n\nAdd my search result: [\nInvalidVersion exception when invalid version used on Setuptools 66\n#3772 ](https://github.com/pypa/setuptools/issues/3772)","files":null},{"type":6,"timestamp":1713565867,"nonce":"mzF18SQcKJZgxqAoZBjWh3F+d4E=","metadata":{"github-id":"UCE_lALOBLCY8M57OS5RzkSfTIk"},"target":"5247880b60e1fe7f988d2099a9efa2d0a419b3cbce693a5e96906c277b924a77","message":"\u003e Try without virtualenv/venv:\n\u003e \n\u003e ```\n\u003e pip3 install --user stdeb\n\u003e python3 ./setup.py --command-packages=stdeb bdist_deb\n\u003e ```\n\nOK, I have googled some issues, which might be related to specific python version. I'm NOT sure if it's python 3.10\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip3 install --user stdeb\nRequirement already satisfied: stdeb in /home/daniel/.local/lib/python3.10/site-packages (0.10.0)\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 ./setup.py --command-packages=stdeb bdist_deb\nTraceback (most recent call last):\n  File \"/home/daniel/wfb/wfb-ng/./setup.py\", line 39, in \u003cmodule\u003e\n    setup(\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/__init__.py\", line 104, in setup\n    return distutils.core.setup(**attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 146, in setup\n    _setup_distribution = dist = klass(attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 318, in __init__\n    self.metadata.version = self._normalize_version(self.metadata.version)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 354, in _normalize_version\n    normalized = str(Version(version))\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\nsetuptools.extern.packaging.version.InvalidVersion: Invalid version: 'trunk'\n```\n\n-- EDIT\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip list | grep setuptools\nsetuptools                   69.5.1\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ which python\n/usr/bin/python\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ ls -l /usr/bin/python\nlrwxrwxrwx 1 root root 7 10月 11  2021 /usr/bin/python -\u003e python3\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 --version\nPython 3.10.12\n```\n\nAdd my search result: [\nInvalidVersion exception when invalid version used on Setuptools 66\n#3772 ](https://github.com/pypa/setuptools/issues/3772)","files":null},{"type":6,"timestamp":1713566688,"nonce":"+xZR1jOttWOnjdMtZw7CAm94YO8=","metadata":{"github-id":"UCE_lALOBLCY8M57OS5RzkSfcz4"},"target":"5247880b60e1fe7f988d2099a9efa2d0a419b3cbce693a5e96906c277b924a77","message":"\u003e Try without virtualenv/venv:\n\u003e \n\u003e ```\n\u003e pip3 install --user stdeb\n\u003e python3 ./setup.py --command-packages=stdeb bdist_deb\n\u003e ```\n\nOK, I have googled some issues, which might be related to specific python version. I'm NOT sure if it's python 3.10\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip3 install --user stdeb\nRequirement already satisfied: stdeb in /home/daniel/.local/lib/python3.10/site-packages (0.10.0)\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 ./setup.py --command-packages=stdeb bdist_deb\nTraceback (most recent call last):\n  File \"/home/daniel/wfb/wfb-ng/./setup.py\", line 39, in \u003cmodule\u003e\n    setup(\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/__init__.py\", line 104, in setup\n    return distutils.core.setup(**attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 146, in setup\n    _setup_distribution = dist = klass(attrs)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 318, in __init__\n    self.metadata.version = self._normalize_version(self.metadata.version)\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/dist.py\", line 354, in _normalize_version\n    normalized = str(Version(version))\n  File \"/home/daniel/.local/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\nsetuptools.extern.packaging.version.InvalidVersion: Invalid version: 'trunk'\n```\n\n-- EDIT\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ pip list | grep setuptools\nsetuptools                   69.5.1\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ which python\n/usr/bin/python\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ ls -l /usr/bin/python\nlrwxrwxrwx 1 root root 7 10月 11  2021 /usr/bin/python -\u003e python3\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ python3 --version\nPython 3.10.12\n```\n\nAdd my search result: [\nInvalidVersion exception when invalid version used on Setuptools 66\n#3772 ](https://github.com/pypa/setuptools/issues/3772)\n\n-- EDIT2, env python versions\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ env/local/bin/pip list|grep setuptools\nsetuptools 59.6.0\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ env/local/bin/python --version\nPython 3.10.12\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ env/local/bin/python3 --version\nPython 3.10.12\n\n```","files":null}]}