{"author":{"id":"b03b656f2973b3294e885873225f3e6827ef890be5b6895978d995675f093aac"},"ops":[{"type":3,"timestamp":1632946384,"nonce":"4zDovI8fPguKyvZeIzWePtfvBQA=","metadata":{"github-id":"IC_kwDOBLCY8M43dm4t","github-url":"https://github.com/svpcom/wfb-ng/issues/167#issuecomment-930508333"},"message":"One more note: I needed to tweak latency_test.py a bit  to be able to run with python3 - but I experienced the same behaviour with python2.","files":null}]}