{"author":{"id":"65067c6c2b3cc812fdd56acf0423f4e61ef64ee5f723791b67959c3592d4712b"},"ops":[{"type":1,"timestamp":1727412017,"nonce":"OWAKWFrAd1uCIig0inabjgRJk5s=","metadata":{"github-id":"I_kwDOBLCY8M6YHB1N","github-url":"https://github.com/svpcom/wfb-ng/issues/373","origin":"github"},"title":"[BUG] install_gs.sh failing: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'","message":"**Describe the bug**\nI'm following the instruction for the Ubuntu Ground Station, everything is working up to `sudo ./scripts/install_gs.sh \u003cmy_specific_wifi_alias_here\u003e`. This is the error I'm getting:\n\n```\nvirtualenv --python=/usr/bin/python3 /home/steve/dev/wfb-ng/env\nTraceback (most recent call last):\n  File \"/usr/bin/virtualenv\", line 5, in \u003cmodule\u003e\n    from virtualenv.__main__ import run_with_catch\n  File \"/usr/lib/python3/dist-packages/virtualenv/__init__.py\", line 3, in \u003cmodule\u003e\n    from .run import cli_run, session_via_cli\n  File \"/usr/lib/python3/dist-packages/virtualenv/run/__init__.py\", line 14, in \u003cmodule\u003e\n    from .plugin.creators import CreatorSelector\n  File \"/usr/lib/python3/dist-packages/virtualenv/run/plugin/creators.py\", line 6, in \u003cmodule\u003e\n    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin\n  File \"/usr/lib/python3/dist-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py\", line 7, in \u003cmodule\u003e\n    from virtualenv.create.creator import Creator\n  File \"/usr/lib/python3/dist-packages/virtualenv/create/creator.py\", line 15, in \u003cmodule\u003e\n    from virtualenv.discovery.cached_py_info import LogCmd\n  File \"/usr/lib/python3/dist-packages/virtualenv/discovery/cached_py_info.py\", line 23, in \u003cmodule\u003e\n    _CACHE[Path(sys.executable)] = PythonInfo()\n  File \"/usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py\", line 86, in __init__\n    self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}\n  File \"/usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py\", line 161, in _distutils_install\n    i.finalize_options()\n  File \"/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py\", line 67, in finalize_options\n    super().finalize_options()\n  File \"/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py\", line 408, in finalize_options\n    'dist_fullname': self.distribution.get_fullname(),\n  File \"/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py\", line 267, in get_fullname\n    return _distribution_fullname(self.get_name(), self.get_version())\n  File \"/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py\", line 285, in _distribution_fullname\n    canonicalize_version(version, strip_trailing_zero=False),\nTypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'\n```\n\n**To Reproduce**\n- From an Ubuntu 22.04 LTS install, follow the normal installation procedure per the README.md: https://github.com/svpcom/wfb-ng?tab=readme-ov-file#quick-start-using-debian-or-ubuntu-ground-station\n- I've tried various means to fix the issue, such as `python -m pip install --upgrade pip setuptools`, or downgrading the setuptools package via `python -m pip install setuptools==70.3.0`. No other steps attempted except `sudo make clean` between attempts at executing `sudo ./scripts/install_gs.sh wlx00c0cab3e254`\n- I have also tried different versions of the project, with `git checkout master`, `git checkout stable`, or other specific releases, with appropriate `git reset --hard HEAD` or equivalent commands to clean the repo state.\n\n**Expected behavior**\nNormal installation per the README.md instructions.\n\n**Your setup (please complete the following information):**\n - Ubuntu 22.04 LTS\n - x86\n - WiFi card not relevant in this case, but 8812au if this must be relevant\n - WiFi drivers from https://github.com/svpcom/rtl8812au.git\n\nAdditional configuration notes:\nPython 3.10.12\npip 24.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)\nPython setuptools version 70.3.0, downgraded from 75.1.0 (I've tried both, downgrading does nothing to correct the issue)\n\n**Additional context**\nI've found the following hints as to why things are breaking, it seems they have changed the behavior by design:\nhttps://github.com/pypa/setuptools/issues/4483\nhttps://github.com/pypa/setuptools/issues/4496\n\nAlso, I've found this closed issue from a few weeks ago, for a similar issue with the build system:\nhttps://github.com/svpcom/wfb-ng/issues/349\n\n\n**Confirm you read**\n- [X]  https://github.com/svpcom/wfb-ng/blob/master/README.md\n- [X]  https://github.com/svpcom/wfb-ng/wiki/Setup-HOWTO","files":null}]}