{"author":{"id":"84c6ab43d9940eb69681dad46f98e5897219811094e1fa877e92eb353e43feae"},"ops":[{"type":3,"timestamp":1560346324,"nonce":"XgWQb0/W7zReq3bukWhX5iP26Pc=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDUwMTI3NDY1OA==","github-url":"https://github.com/svpcom/wfb-ng/issues/39#issuecomment-501274658"},"message":"i ordered two yesterday and they literally arrived 10 mins ago.\n\nthank you i will try it all again now.","files":null},{"type":3,"timestamp":1560350110,"nonce":"hoxXWMOQ/bsiVPlIl9nKXAn2YBk=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDUwMTMwMjE2Ng==","github-url":"https://github.com/svpcom/wfb-ng/issues/39#issuecomment-501302166"},"message":"i have followed all the instructions and i am getting the current error.  Any help would be great\n\nroot@nanopineocore2:/# systemctl status wifibroadcast@gs\n* wifibroadcast@gs.service - WFB profile gs\n   Loaded: loaded (/lib/systemd/system/wifibroadcast@.service; disabled; vendor preset: enabled)\n   Active: active (running) since Wed 2019-06-12 14:33:40 UTC; 11ms ago\n Main PID: 3115 (python)\n    Tasks: 1 (limit: 4915)\n   CGroup: /system.slice/system-wifibroadcast.slice/wifibroadcast@gs.service\n           `-3115 /usr/bin/python -m telemetry.server gs wlx24050ff7306a\n\nJun 12 14:33:40 nanopineocore2 systemd[1]: Started WFB profile gs.\nroot@nanopineocore2:/# systemctl status wifibroadcast@gs\n* wifibroadcast@gs.service - WFB profile gs\n   Loaded: loaded (/lib/systemd/system/wifibroadcast@.service; disabled; vendor preset: enabled)\n   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-06-12 14:33:40 UTC; 37ms ago\n  Process: 3115 ExecStart=/usr/bin/python -m telemetry.server gs ${WFB_NICS} (code=exited, status=1/FAILURE)\n Main PID: 3115 (code=exited, status=1/FAILURE)","files":null}]}