{"author":{"id":"01f22aa59e3c8c6a5b890b43d7b9549418cedb995a54fe4e7e2f5845fa84afdd"},"ops":[{"type":3,"timestamp":1549101514,"nonce":"jW+vKoveRU+KInMwDvy1gIOhr60=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ1OTk1MjE3NQ==","github-url":"https://github.com/svpcom/wfb-ng/issues/30#issuecomment-459952175"},"message":"It's not related to this project but I'm a little confused after setting things up:\nmavlink-router config:\n[UartEndpoint PX4]\nDevice = /dev/ttyAMA0\nBaud = 921600\n[UdpEndpoint MyApp]\nMode = Normal\nAddress = 127.0.0.1\nPort = 11000\n\nI tried to connect to UAV(PX4) and do some tweaking with below code:\n```\nmav = mavutil.mavlink_connection('udpin:127.0.0.1:11000') \nmav.wait_heartbeat()\n# below fails\nmav.set_mode(mode_id)\n```\nsome how the set_mode doesn't work. I tried several variants and none works and mavlink router reported:\n\"1 messages to unknown endpoints in the last 5 seconds\"\nAs I searched, some one mentioned the correct connection string should be something \"udpout:0.0.0.0ï¼šsome_port\".\n\nAny idea what should be done to fix this?\nThanks for any idea.","files":null},{"type":3,"timestamp":1549103668,"nonce":"LVoY17U7jQTAvF6ZrYWGnvowqxw=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ1OTk1NDQ3NQ==","github-url":"https://github.com/svpcom/wfb-ng/issues/30#issuecomment-459954475"},"message":"I tried to use mavlink-router/examples/arm.py by \"python arm.py 127.0.0.1:14550\" on RX and same \"1 messages to unknown endpoints in the last 5 seconds\" printed on TX. \nIt seems the message is not correctly parsed?","files":null}]}